spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    server:
      port=3535:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 30000 # 30 seconds
      connection-test-query: SELECT 1
      validation-timeout: 6000 # 6 seconds
      idle-timeout: 600000 # 10 minutes
      max-lifetime: 1800000 # 30 minutes
      pool-name: SecurityDBHikariCP

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        use_sql_comments: false